title: test1
description: 'this is my first attempt to use the Github, now I would like to explore some. '
template:
  repo: test1-template
  name: test1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
